// GENERATED by scripts/build-audio-tour.mjs — do not hand-edit.
//
// Burning Man's 2026 Art Audio Tour, matched to the artworks we list.
// Audio is served from public/audio/tour and is deliberately NOT precached by
// the service worker — 57 MB of narration has no business in an offline shell.

export interface AudioTrack {
  /** the tour's own numbering, 0 = introduction */
  n: number
  /** artwork name as the tour announces it */
  title: string
  /** path under /audio/tour */
  file: string
}

/** The tour's introduction and the theme talk — not tied to any artwork. */
export const TOUR_EXTRAS: AudioTrack[] = [
  { n: 0, title: "Introduction -2026 Burning Man Audio Art Guide - Axis Mundi", file: "00-introduction-2026-burning-man-audio-art-guide-axis-mundi.m4a" },
  { n: 87, title: "The Theme - Burning Man 2026 - Axis Mundi by Stewart Mangrum 10.3.2025", file: "87-the-theme-burning-man-2026-axis-mundi-by-stewart-mangrum-10-.m4a" },
]

/** One track per artwork, in tour order. */
export const TOUR_TRACKS: AudioTrack[] = [
  { n: 1, title: "Temple of the Moon", file: "01-temple-of-the-moon.m4a" },
  { n: 2, title: "Axis Mundi: Resonant Spire", file: "02-axis-mundi-resonant-spire.m4a" },
  { n: 3, title: "Brews 12 v Uno: cLOUD OF WIT-nesses", file: "03-brews-12-v-uno-cloud-of-wit-nesses.m4a" },
  { n: 4, title: "Mangrovito", file: "04-mangrovito.m4a" },
  { n: 5, title: "Aetheric Ascension Tower", file: "05-aetheric-ascension-tower.m4a" },
  { n: 6, title: "Carnac 2026", file: "06-carnac-2026.m4a" },
  { n: 7, title: "Limen", file: "07-limen.m4a" },
  { n: 8, title: "Bless My Meat", file: "08-bless-my-meat.m4a" },
  { n: 9, title: "Do Baskets Dream of Shores or Sea", file: "09-do-baskets-dream-of-shores-or-sea.m4a" },
  { n: 10, title: "Freedom Dancers", file: "10-freedom-dancers.m4a" },
  { n: 11, title: "Sanctuary of the Silent Star", file: "11-sanctuary-of-the-silent-star.m4a" },
  { n: 12, title: "Seven Sisters", file: "12-seven-sisters.m4a" },
  { n: 13, title: "CORREFOC", file: "13-correfoc.m4a" },
  { n: 14, title: "ALUNA The Frequency of Being", file: "14-aluna-the-frequency-of-being.m4a" },
  { n: 15, title: "Dusty Heart, Tumbleweed Soul", file: "15-dusty-heart-tumbleweed-soul.m4a" },
  { n: 16, title: "Behind Closed Eyes", file: "16-behind-closed-eyes.m4a" },
  { n: 17, title: "Above and Below", file: "17-above-and-below.m4a" },
  { n: 18, title: "Confessional Alter: Demoop du Soul", file: "18-confessional-alter-demoop-du-soul.m4a" },
  { n: 19, title: "the weight of light", file: "19-the-weight-of-light.m4a" },
  { n: 20, title: "Octopolis", file: "20-octopolis.m4a" },
  { n: 21, title: "The Race of Hearts", file: "21-the-race-of-hearts.m4a" },
  { n: 22, title: "Resonance Tree", file: "22-resonance-tree.m4a" },
  { n: 23, title: "Mundara", file: "23-mundara.m4a" },
  { n: 24, title: "LOOKOUT", file: "24-lookout.m4a" },
  { n: 25, title: "Purrmaid", file: "25-purrmaid.m4a" },
  { n: 26, title: "Aikido – The Mothership Connection", file: "26-aikido-the-mothership-connection.m4a" },
  { n: 27, title: "Totem of Transformation, The Shifting Balance", file: "27-totem-of-transformation-the-shifting-balance.m4a" },
  { n: 28, title: "The Serpent", file: "28-the-serpent.m4a" },
  { n: 29, title: "Resilience", file: "29-resilience.m4a" },
  { n: 30, title: "1:1000 - A Wish for Recovery", file: "30-1-1000-a-wish-for-recovery.m4a" },
  { n: 31, title: "NO", file: "31-no.m4a" },
  { n: 32, title: "Our own Devices", file: "32-our-own-devices.m4a" },
  { n: 33, title: "epod", file: "33-epod.m4a" },
  { n: 34, title: "The Love Nest", file: "34-the-love-nest.m4a" },
  { n: 35, title: "Pandora:s Eye", file: "35-pandora-s-eye.m4a" },
  { n: 36, title: "Just A Spoonful", file: "36-just-a-spoonful.m4a" },
  { n: 37, title: "Honey", file: "37-honey.m4a" },
  { n: 38, title: "Harmonic Orbiter", file: "38-harmonic-orbiter.m4a" },
  { n: 39, title: "Yggdrasil", file: "39-yggdrasil.m4a" },
  { n: 40, title: "Project O.C.T.O.P.U.S.", file: "40-project-o-c-t-o-p-u-s.m4a" },
  { n: 41, title: "Nang Du: the nanganing (a trailer trash epic)", file: "41-nang-du-the-nanganing-a-trailer-trash-epic.m4a" },
  { n: 42, title: "Rise (Float On)", file: "42-rise-float-on.m4a" },
  { n: 43, title: "ZARVAN", file: "43-zarvan.m4a" },
  { n: 44, title: "Shoe Tree", file: "44-shoe-tree.m4a" },
  { n: 45, title: "Penny the Goose", file: "45-penny-the-goose.m4a" },
  { n: 46, title: "Iguana-na", file: "46-iguana-na.m4a" },
  { n: 47, title: "The Flaming Carousel", file: "47-the-flaming-carousel.m4a" },
  { n: 48, title: "Coming Home", file: "48-coming-home.m4a" },
  { n: 49, title: "As Above, So Within", file: "49-as-above-so-within.m4a" },
  { n: 50, title: "Beetle", file: "50-beetle.m4a" },
  { n: 51, title: "QUEEN: Quantum Universal Epic Era Now!", file: "51-queen-quantum-universal-epic-era-now.m4a" },
  { n: 52, title: "THE TEAR OF MIDAS", file: "52-the-tear-of-midas.m4a" },
  { n: 53, title: "Elemental Dragon", file: "53-elemental-dragon.m4a" },
  { n: 54, title: "Kaleidoscope", file: "54-kaleidoscope.m4a" },
  { n: 55, title: "The Portal of Collective Imagination", file: "55-the-portal-of-collective-imagination.m4a" },
  { n: 56, title: "Apotheneum", file: "56-apotheneum.m4a" },
  { n: 57, title: "The Council of Animals, What to Do about the Humans", file: "57-the-council-of-animals-what-to-do-about-the-humans.m4a" },
  { n: 58, title: "Keyhole to Other Dimensions", file: "58-keyhole-to-other-dimensions.m4a" },
  { n: 59, title: "Playa Penguins", file: "59-playa-penguins.m4a" },
  { n: 60, title: "PULSE", file: "60-pulse.m4a" },
  { n: 61, title: "On High", file: "61-on-high.m4a" },
  { n: 62, title: "EIFFELA BROKEN DREAM", file: "62-eiffela-broken-dream.m4a" },
  { n: 63, title: "Tree of Photon", file: "63-tree-of-photon.m4a" },
  { n: 64, title: "Compost Playground", file: "64-compost-playground.m4a" },
  { n: 65, title: "Petaled Portal", file: "65-petaled-portal.m4a" },
  { n: 66, title: "Disco Mushroom", file: "66-disco-mushroom.m4a" },
  { n: 67, title: "The Royal Trumpets", file: "67-the-royal-trumpets.m4a" },
  { n: 68, title: "We the Sheeple", file: "68-we-the-sheeple.m4a" },
  { n: 69, title: "Fire Gnome", file: "69-fire-gnome.m4a" },
  { n: 70, title: "The Speed of the Earth 2026", file: "70-the-speed-of-the-earth-2026.m4a" },
  { n: 71, title: "Mebuyan Pulse", file: "71-mebuyan-pulse.m4a" },
  { n: 72, title: "For They Know Not What They Do", file: "72-for-they-know-not-what-they-do.m4a" },
  { n: 73, title: "TITANIC", file: "73-titanic.m4a" },
  { n: 74, title: "The Garage", file: "74-the-garage.m4a" },
  { n: 75, title: "Cocoon", file: "75-cocoon.m4a" },
  { n: 76, title: "Dusty Corner of the Capital", file: "76-dusty-corner-of-the-capital.m4a" },
  { n: 77, title: "Acinonyx", file: "77-acinonyx.m4a" },
  { n: 78, title: "The Gothic Folly", file: "78-the-gothic-folly.m4a" },
  { n: 79, title: "D.A.R.E – Does Art Reside Everywhere?", file: "79-d-a-r-e-does-art-reside-everywhere.m4a" },
  { n: 80, title: "Spectral Scarab", file: "80-spectral-scarab.m4a" },
  { n: 81, title: "Heart Remains", file: "81-heart-remains.m4a" },
  { n: 82, title: "The Circle of Ancestors", file: "82-the-circle-of-ancestors.m4a" },
  { n: 83, title: "Notorious BIG Spinning Wheels", file: "83-notorious-big-spinning-wheels.m4a" },
  { n: 84, title: "Headwaters", file: "84-headwaters.m4a" },
  { n: 85, title: "The Sound of Time", file: "85-the-sound-of-time.m4a" },
  { n: 86, title: "Giraffe in Motion", file: "86-giraffe-in-motion.m4a" },
]

/** Normalised artwork name → track. Matching is by name because the audio ships
 *  with the repo while art rows carry per-environment ids. */
export function normalizeArtName(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

const BY_NAME = new Map(TOUR_TRACKS.map(t => [normalizeArtName(t.title), t]))

/** The tour track for an artwork, or null if it has none. */
export function audioForArt(name: string | null | undefined): AudioTrack | null {
  return (name && BY_NAME.get(normalizeArtName(name))) || null
}

/** Public URL for a track. */
export function audioUrl(t: AudioTrack): string {
  return `/audio/tour/${t.file}`
}
